#
# === Sparkbadge Config ===
#

# ===== General Setup =====
[general]
id = "facebook/react"
timeframe = "full"
base_url = "https://api.github.com/repos"

# ===== COMMITS =====
[commits]

[commits.input]
until = ""
since = ""

[commits.output]



# ===== ISSUES =====
[issues]

[issues.input]

[issues.output]


# ===== RUNS =====
[runs]

[runs.input]

[runs.output]
